url: https://oceanomi.github.io/error
baseurl: .

# Site settings
title: Error
email: carolina@carolinapodesta.com
author: "Carolina Podesta"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 094feb
  secondary: 147765
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  scope:
    path: ""
    type: "posts"
  values:
    layout: "default"
